[package]
name = "car-go"
version = "0.1.0"
authors = ["TheAdnan <adnankicin92@gmail.com>"]
[[bin]]
name = "car-go"

[dependencies]
piston_window = "0.70.0"
pistoncore-glutin_window = "0.43.0"
piston2d-graphics = "0.24.0"
piston2d-opengl_graphics = "0.50.0"
piston = "0.35.0"
